// src/lib/header/Header.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import logo from "./svelte-logo.svg";
</script>

<header>
  <div class="corner">
    <a href="https://kit.svelte.dev">
      <img src={logo} alt="SvelteKit" />
    </a>
  </div>

  <nav>
    <svg viewBox="0 0 2 3" aria-hidden="true">
      <path d="M0,0 L1,2 C1.5,3 1.5,3 2,3 L2,0 Z" />
    </svg>
    <ul>
      <li class:active={$page.path === "/"}><a sveltekit:prefetch href="/">Home</a></li>
      <li class:active={$page.path === "/about"}><a sveltekit:prefetch href="/about">About</a></li>
      <li class:active={$page.path === "/todos"}><a sveltekit:prefetch href="/todos">Todos</a></li>
    </ul>
    <svg viewBox="0 0 2 3" aria-hidden="true">
      <path d="M0,0 L0,3 C0.5,3 0.5,3 1,2 L2,0 Z" />
    </svg>
  </nav>

  <div class="corner">
    <!-- TODO put something else here? github link? -->
  </div>
</header>

<style>
  header {
    display: flex;
    justify-content: space-between;
  }

  .corner {
    width: 3em;
    height: 3em;
  }

  .corner a {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
  }

  .corner img {
    width: 2em;
    height: 2em;
    object-fit: contain;
  }

  nav {
    display: flex;
    justify-content: center;
    --background: rgba(255, 255, 255, 0.7);
  }

  svg {
    width: 2em;
    height: 3em;
    display: block;
  }

  path {
    fill: var(--background);
  }

  ul {
    position: relative;
    padding: 0;
    margin: 0;
    height: 3em;
    display: flex;
    justify-content: center;
    align-items: center;
    list-style: none;
    background: var(--background);
    background-size: contain;
  }

  li {
    position: relative;
    height: 100%;
  }

  li.active::before {
    --size: 6px;
    content: "";
    width: 0;
    height: 0;
    position: absolute;
    top: 0;
    left: calc(50% - var(--size));
    border: var(--size) solid transparent;
    border-top: var(--size) solid var(--accent-color);
  }

  nav a {
    display: flex;
    height: 100%;
    align-items: center;
    padding: 0 1em;
    color: var(--heading-color);
    font-weight: 700;
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    text-decoration: none;
    transition: color 0.2s linear;
  }

  a:hover {
    color: var(--accent-color);
  }
</style>

// src/components/Header.vue
<template>
  <header
    class="header"
    :class="{sticky: $route.path === '/', 'is-primary': this.$store.getters.isPrimary && $route.path === '/'}"
  >
    <div class="container">
      <div class="nav left">
        <g-link class="nav__link" to="/">Home</g-link>
      </div>
      <nav class="nav right">
        <g-link class="nav__link" to="/about">About</g-link>
        <g-link class="nav__link" to="/journal">Journal</g-link>
        <g-link class="nav__link" to="/contact">Contact</g-link>
      </nav>
    </div>
  </header>
</template>

<script>
export default {
  data() {
    return {
      settings: require('../../data/theme.json'),
    }
  },
}
</script>

<style lang="sass" scoped>
.header
  position: relative
  height: 3rem
  z-index: 10
  background-color: white
  &.is-primary
    background-color: rgba(0, 0, 0, 0)
    a
      color: white!important
      opacity: 0.75


.header.sticky
  position: fixed
  top: 0
  left: 0
  width: 100%

.header > .container
  display: flex
  align-items: center
  justify-content: space-between
  height: 100%

.home-link
  text-decoration: none

.logo
  height: 1.5rem

.site-name
  font-size: 0.9rem
  font-weight: 700
  letter-spacing: 0.05em
  text-decoration: none
  text-transform: uppercase

.nav > *
  font-size: 0.9rem
  font-weight: 600
  text-decoration: none
  margin-top: 4px
  margin-right: 3rem
  padding-bottom: 4px
  border-bottom: 1px solid
  border-color: transparent
  transition: border 0.15s

  @media (max-width: 400px)
    margin-right: 1rem
  @media (max-width: 300px)
    margin-right: 0.5rem

.nav > *:last-of-type
  margin: 0

.nav > *:hover
  border-color: inherit

.nav > .active--exact
  border-color: inherit

</style>
