// src/components/Header.vue
<template>
  <header
    class="header"
    :class="{sticky: $route.path === '/', 'is-primary': this.$store.getters.isPrimary && $route.path === '/'}"
  >
    <div class="container">
      <div class="nav left">
        <g-link class="nav__link" to="/">Home</g-link>
      </div>
      <nav class="nav right">
        <g-link class="nav__link" to="/about">About</g-link>
        <g-link class="nav__link" to="/journal">Journal</g-link>
        <g-link class="nav__link" to="/contact">Contact</g-link>
      </nav>
    </div>
  </header>
</template>

<script>
export default {
  data() {
    return {
      settings: require('../../data/theme.json'),
    }
  },
}
</script>

<style lang="sass" scoped>
.header
  position: relative
  height: 3rem
  z-index: 10
  background-color: white
  &.is-primary
    background-color: rgba(0, 0, 0, 0)
    a
      color: white!important
      opacity: 0.75


.header.sticky
  position: fixed
  top: 0
  left: 0
  width: 100%

.header > .container
  display: flex
  align-items: center
  justify-content: space-between
  height: 100%

.home-link
  text-decoration: none

.logo
  height: 1.5rem

.site-name
  font-size: 0.9rem
  font-weight: 700
  letter-spacing: 0.05em
  text-decoration: none
  text-transform: uppercase

.nav > *
  font-size: 0.9rem
  font-weight: 600
  text-decoration: none
  margin-top: 4px
  margin-right: 3rem
  padding-bottom: 4px
  border-bottom: 1px solid
  border-color: transparent
  transition: border 0.15s

  @media (max-width: 400px)
    margin-right: 1rem
  @media (max-width: 300px)
    margin-right: 0.5rem

.nav > *:last-of-type
  margin: 0

.nav > *:hover
  border-color: inherit

.nav > .active--exact
  border-color: inherit

</style>

// src/components/Header.svelte
<script lang="ts">
  import { page } from "$app/stores"
</script>

<header class="bg-background p-4 flex justify-center">
  <nav class="flex justify-center">
    <ul class="relative p-0 m-0 flex justify-center items-center bg-contain h-12 list-none">
      <li class:active={$page.path === "/"}><a sveltekit:prefetch href="/">Home</a></li>
      <li class:active={$page.path === "/about"}><a sveltekit:prefetch href="/about">About</a></li>
      <li class:active={$page.path.includes("/journal")}>
        <a sveltekit:prefetch href="/journal">Journal</a>
      </li>
      <li class:active={$page.path === "/contact"}>
        <a sveltekit:prefetch href="/contact">Contact</a>
      </li>
    </ul>
  </nav>
</header>

<style lang="postcss">
  li {
    position: relative;
    height: 100%;

    &.active::before {
      content: "";
      width: 0;
      height: 0;
      position: absolute;
      bottom: 0;
      left: calc(50% - 8px);
      border: 8px solid transparent;
      @apply border-b-primary;
    }
  }

  nav a {
    display: flex;
    height: 100%;
    align-items: center;
    padding: 0 1em;
    color: #fff;
    font-weight: 700;
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    text-decoration: none;
    transition: color 0.2s linear;

    &:hover {
      @apply text-primary;
    }
  }
</style>
